package view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Andrey da Silva Rodrigues
 */
public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        this.initCardLayout();
    }

    private void initCardLayout() {
        this.telaPrincipal = new TelaPrincipal();
        this.superNintendo = new SuperNintendo();
        this.configuracoes = new Configuracoes();
        
        this.jpPrincipal.add(this.telaPrincipal, "telaPrincipal");
        this.jpPrincipal.add(this.superNintendo, "superNintendo");
        this.jpPrincipal.add(this.configuracoes, "configuracoes");
        
        layout = (CardLayout) this.jpPrincipal.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPEmuladores = new javax.swing.JPanel();
        jbTelaPrincipal = new javax.swing.JButton();
        jbSuperNintendo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbConfiguracoes = new javax.swing.JButton();
        jpPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        JPEmuladores.setLayout(new java.awt.GridLayout());

        jbTelaPrincipal.setText("Tela Principal");
        jbTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTelaPrincipalActionPerformed(evt);
            }
        });
        JPEmuladores.add(jbTelaPrincipal);

        jbSuperNintendo.setText("Super Nintendo");
        jbSuperNintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuperNintendoActionPerformed(evt);
            }
        });
        JPEmuladores.add(jbSuperNintendo);

        jButton2.setText("Emulador 2");
        JPEmuladores.add(jButton2);

        jButton3.setText("Emulador 3");
        JPEmuladores.add(jButton3);

        jbConfiguracoes.setText("Configurações");
        jbConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfiguracoesActionPerformed(evt);
            }
        });
        JPEmuladores.add(jbConfiguracoes);

        jpPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPEmuladores, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPEmuladores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSuperNintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuperNintendoActionPerformed
        this.layout.show(this.jpPrincipal, "superNintendo");
    }//GEN-LAST:event_jbSuperNintendoActionPerformed

    private void jbTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTelaPrincipalActionPerformed
        this.layout.show(this.jpPrincipal, "telaPrincipal");
    }//GEN-LAST:event_jbTelaPrincipalActionPerformed

    private void jbConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfiguracoesActionPerformed
        this.layout.show(this.jpPrincipal, "configuracoes");
    }//GEN-LAST:event_jbConfiguracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPEmuladores;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jbConfiguracoes;
    private javax.swing.JButton jbSuperNintendo;
    private javax.swing.JButton jbTelaPrincipal;
    private javax.swing.JPanel jpPrincipal;
    // End of variables declaration//GEN-END:variables
    
    private CardLayout layout;
    
    private JPanel telaPrincipal;
    
    private JPanel superNintendo;
    
    private JPanel configuracoes;

}
